#server:
#  port: 4020
#
#spring:
#  application:
#    name: Api-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: User-Service
#          uri: lb://User-Service
#          predicates:
#            - name: Path
#              args:
#                pattern: /api/user/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: user-service
#                fallbackuri: forward:/userServiceFallBack
#        - id: Profile-Service
#          uri: lb://Profile-Service
#          predicates:
#            - name: Path
#              args:
#                pattern: /api/user/profile/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: Profile-Service
#                fallbackuri: forward:/Profile-ServiceFallBack
#
#eureka:
#  instance:
#    hostname: localhost
#
#hystrix:
#  command:
#    fallbackcmd:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5000
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream
